### ISSUE TITLE
Upgrade to 7.0.1: PaymentPageUrl: impossible to sent content with this verb

### ISSUE THREAD

**Issue by Netclick19** [pfpayments/csharp-sdk#10]
Hi,

after update to 7.0.1 i have some problem with a call (before I'm using version 5).

var transaction = transactionService.CreateWithHttpInfo(spaceId, transactionCreate);
if (transaction != null)
{
    var transactionPaymentPageService = new TransactionPaymentPageService(configuration);
    var paymentPageUrl = transactionPaymentPageService.PaymentPageUrl(spaceId, transaction.Data.Id);
    return Redirect(paymentPageUrl);
}

//On this method I got a new error 
**_var paymentPageUrl = transactionPaymentPageService.PaymentPageUrl(spaceId, transaction.Data.Id);_**

PostFinanceCheckout.Client.ApiException: 'Error calling PaymentPageUrl: Impossibile inviare un contenuto con questo tipo di verbo.'
   in PostFinanceCheckout.Service.TransactionPaymentPageService.PaymentPageUrlWithHttpInfo(Nullable`1 spaceId, Nullable`1 id)
   in PostFinanceCheckout.Service.TransactionPaymentPageService.PaymentPageUrl(Nullable`1 spaceId, Nullable`1 id)

SpaceId is compiled and transaction.data.id has the value I received from the first call.

Can you help to solve this problem?

Thank you for your problem.

Sacha

**Comment by theodorspringwallee** [comment]
Dear [Netclick19](https://github.com/Netclick19)

The transaction ID is `transaction.Id` (and not transaction.Data.Id).

Here I have a workable code example (just use your auth credentials and your wished currency):
```
public class PFCServiceHelperClass
{
    private TransactionService transactionService;
    private TransactionPaymentPageService transactionPaymentPageService;
    private long spaceId;
    private String appUserId;
    private String appUserKey;

    public PFCServiceHelperClass()
    {
        this.spaceId = ;
        this.appUserId = "";
        this.appUserKey = "";
        var configuration = new Configuration(this.appUserId, this.appUserKey);
        this.transactionService = new TransactionService(configuration);
        this.transactionPaymentPageService = new TransactionPaymentPageService(configuration);
    }

    static void Main(string[] args)
    {
        try
        {
            PFCServiceHelperClass pfcServiceHelperClass = new PFCServiceHelperClass();


            LineItemCreate lineItem1 = new LineItemCreate(
                name: "Item 1",
                uniqueId: "unique-id-item-1",
                type: LineItemType.PRODUCT,
                quantity: 1,
                amountIncludingTax: (decimal) 67.47
            );
            lineItem1.Sku = "item-1";
            TransactionCreate transactionCreate = new TransactionCreate(new List<LineItemCreate>() { lineItem1 });
            transactionCreate.Currency = "CHF";
            Transaction transaction = pfcServiceHelperClass.transactionService.Create(pfcServiceHelperClass.spaceId, transactionCreate);
            if(transaction != null)
            {
                var paymentPageUrl = pfcServiceHelperClass.transactionPaymentPageService.PaymentPageUrl(pfcServiceHelperClass.spaceId, transaction.Id);
                System.Console.WriteLine(paymentPageUrl);
            }


        }
        catch (Exception ex)
        {
            System.Console.Write("Exception: " + ex.Message.ToString());
            System.Console.Write("Exception: " + ex.StackTrace.ToString());
        }
    }

}
```

I hope this helps.

Best regards

**Comment by Netclick19** [comment]
Hi,

I've tryed to change my code from:
var transaction = transactionService.CreateWithHttpInfo(spaceId, transactionCreate);
to
var transaction = transactionService.Create(spaceId, transactionCreate);
to use transaction.Id instead of transaction.Data.Id but nothing change.

![image](https://github.com/pfpayments/csharp-sdk/assets/9130333/7829c0d6-8b2b-41bd-a6bc-d5c9edff71b8)

I'm using the same code since one year and always working well. I'm trying to update the psf sdk but only after the upgrade the problems has begun.

**Comment by theodorspringwallee** [comment]
Dear [Netclick19](https://github.com/Netclick19)

Can you try first my code and if it works, you can implement your code part into the working code structure?

Would that be an option for you?

If not, please send your code to the PF Support (https://www.postfinance.ch/en/support/products/onlineshop-pos/postfinance-checkout-contact-and-support.html).

Best regards

**Comment by Netclick19** [comment]
Hi, 
sure I'm trying to do that, but my code is quite the same.

var spaceId = DefaultValueHelper.SpaceId;
var applicationId = DefaultValueHelper.ApplicationId;
var authenticationKey = DefaultValueHelper.ApplicationKey;
var configuration = new Configuration(applicationId + "", authenticationKey);
var transactionService = new TransactionService(configuration);
var customerService = new CustomerService(configuration);
Customer customer = null;

var url = Request.Url.Scheme + "://" + Request.Url.Authority;

                    #region Creazione e generazione del cliente

                    //Imposto i filtri per cliente
                    var filters = new List<EntityQueryFilter>
                    {
                        new EntityQueryFilter(EntityQueryFilterType.LEAF)
                        {
                            FieldName = "customerId",
                            Operator = CriteriaOperator.EQUALS,
                            Value = paymentInfo.customerID
                        }/*,
                        new EntityQueryFilter(EntityQueryFilterType.LEAF)
                        {
                            FieldName = "familyName",
                            Operator = CriteriaOperator.EQUALS,
                            Value = paymentInfo.LastName
                        },
                        new EntityQueryFilter(EntityQueryFilterType.LEAF)
                        {
                            FieldName = "givenName",
                            Operator = CriteriaOperator.EQUALS,
                            Value = paymentInfo.FirstName
                        }*/
                    };

                    var entityQuery = new EntityQuery
                    {
                        Filter = new EntityQueryFilter(EntityQueryFilterType.AND)
                        {
                            Children = filters
                        }
                    };

                    //Ricerco il tentativo di pagamento
                    var customers = customerService.Search(spaceId, entityQuery);

                    //Verifico se ci sono stati tentativi andati a buon fine.
                    if (!customers.Any())
                    {
                        //Creo il cliente se non lo trovo
                        var customerCreate = new CustomerCreate()
                        {
                            CustomerId = paymentInfo.customerID + "",
                            FamilyName = paymentInfo.LastName,
                            GivenName = paymentInfo.FirstName,
                            EmailAddress = paymentInfo.EMAIL,
                            PreferredCurrency = paymentInfo.currency
                        };

                        //Genero la transazione
                        var customerTransaction = customerService.CreateWithHttpInfo(spaceId, customerCreate);

                        //Se ho creato il cliente, gestisco l'informazione.
                        if (customerTransaction != null && customerTransaction.StatusCode == 200)
                        {
                            customer = customerTransaction.Data;
                        }
                    }
                    else
                    {
                        customer = customers.FirstOrDefault();
                    }

                    #endregion

                    #region Creazione e generazione della transazione

                    AddressCreate billingAddress = new AddressCreate
                    {
                        Gender = Gender.MALE,
                        Salutation = "", //"Ms",
                        OrganizationName = "", //"Test GmbH",
                        GivenName = paymentInfo.FirstName, //"Good",
                        FamilyName = paymentInfo.LastName, //"Customer",
                        DateOfBirth = new DateTime(1988, 4, 19),
                        Postcode = paymentInfo.ownerZIP, //"8400",
                        City = paymentInfo.ownertown, //"Winterthur",
                        Country = paymentInfo.ownercty, //"CH",
                        MobilePhoneNumber = "", //"+41791234567",
                        EmailAddress = paymentInfo.EMAIL //"test@example.com"
                    };

                    LineItemCreate lineItem1 = new LineItemCreate(
                        name: paymentInfo.COM,
                        uniqueId: paymentInfo.orderID,
                        type: LineItemType.PRODUCT,
                        quantity: 1,
                        amountIncludingTax: Convert.ToDecimal(paymentInfo.amount)
                    )
                    {
                        Sku = paymentInfo.TITLE,
                        ShippingRequired = false
                    };

                    var transactionCreate = new TransactionCreate(new List<LineItemCreate> { lineItem1 })
                    {
                        CustomerId = customer.CustomerId,
                        MerchantReference = paymentInfo.orderID,
                        BillingAddress = billingAddress,
                        //ShippingAddress = billingAddress,
                        CustomerEmailAddress = billingAddress.EmailAddress,
                        InvoiceMerchantReference = paymentInfo.TITLE,
                        SuccessUrl = url + "/PaymentCheckout/PaymentAccepted?orderId=" + paymentInfo.orderID,
                        FailedUrl = url + "/PaymentCheckout/PaymentException?orderId=" + paymentInfo.orderID,
                        CompletionBehavior = TransactionCompletionBehavior.COMPLETE_IMMEDIATELY,
                        ChargeRetryEnabled = false,
                        AutoConfirmationEnabled = true,
                        Language = paymentInfo.language,
                        Currency = paymentInfo.currency
                    };

                    try
                    {
                        //Genero la transazione
                        var transaction = transactionService.Create(spaceId, transactionCreate);
                        //var transaction = transactionService.CreateWithHttpInfo(spaceId, transactionCreate);

                        //Se ho creato la transazione, recupero la transazione di pagamento memorizzata.
                        if (transaction != null)
                        {
                            //Recupero la transazione memorizzata
                            var paymentTransaction = WebService.GetPaymentTransactionFromOrderId(paymentInfo.orderID);

                            //Verifico se la transazione è valida.
                            if (paymentTransaction != null)
                            {
                                //Associo la transazione
                                paymentTransaction.transactionid = transaction.Id.ToString();

                                //Aggiorno la transazione di pagamento.
                                WebService.UpdatePaymentTransaction(paymentTransaction, true);
                            }

                            //Instanzio il servizio per la generazione dell'URL di pagamento
                            var transactionPaymentPageService = new TransactionPaymentPageService(configuration);

                            //Recupero l'URL per la transazione di pagamento
                            var paymentPageUrl = transactionPaymentPageService.PaymentPageUrl(spaceId, transaction.Id);

                            //Rimando alla pagina di pagamento.
                            return Redirect(paymentPageUrl);
                        }
                    }
                    catch (ApiException e)
                    {
                        Console.WriteLine(e.ToString());
                    }

                    #endregion

**Comment by Netclick19** [comment]
I've tryed with your code and the code generate in the official documentation (https://checkout.postfinance.ch/api/client/transaction-payment-page-service--payment-page-url). 
The error is the same.
I try to write to support.

Kind regards.
