### ISSUE TITLE
Cannot convert null value to PostFinanceCheckout.Model.WalletType. Path '[0].walletType', line 1, position 18728

### ISSUE THREAD

**Issue by Netclick19** [pfpayments/csharp-sdk#5]
Hi,

I receive this message when I try to search a ChargeAttempt.

ApiException: Cannot convert null value to PostFinanceCheckout.Model.WalletType. Path '[0].walletType', line 1, position 18728.
--
Stack Trace | at PostFinanceCheckout.Client.ApiClient.Deserialize(IRestResponse response, Type type)     at PostFinanceCheckout.Service.ChargeAttemptService.SearchWithHttpInfo(Nullable`1 spaceId, EntityQuery query)     at PostFinanceCheckout.Service.ChargeAttemptService.Search(Nullable`1 spaceId, EntityQuery query)

Version: 4.3.8

With version 4.2.0 there are no problems.

this happens with the last version.

Thank you for your support.

Kind regards.

**Comment by theodorspringwallee** [comment]
Dear [Netclick19](https://github.com/Netclick19)

Our developers will check this. We will let you know, when we have a fix for this.

Best regards

**Comment by Netclick19** [comment]
Hi,

do you have any news on it?

Thank you for your support.

Kind regards.

**Comment by theodorspringwallee** [comment]
Dear [Netclick19](https://github.com/Netclick19)

From what I can see from our developers, the mentioned issue is fixed now. 
So you can install the newest SDK version.

Best regards
