### ISSUE TITLE
Switch to .Net 6 oder 7

### ISSUE THREAD

**Issue by GeroL** [pfpayments/csharp-sdk#6]
Hi,

you may want to consider a more up to date version since .Net 5 is out of support since 2022-05-10

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Best regards

**Comment by theodorspringwallee** [comment]
Dear [GeroL](https://github.com/GeroL)

Our developers will check this. Thank you for raising this point.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [GeroL](https://github.com/GeroL)

Our developers recently tested against .NET 6 & 7 with positive results.

Get more information about the compatibility at: https://www.nuget.org/packages/PostFinanceCheckout/#supportedframeworks-body-tab

Best regards
