### ISSUE TITLE
Support of last version of RestSharp

### ISSUE THREAD

**Issue by Eskissimo** [pfpayments/csharp-sdk#7]
Hi,

Did you plan to support the last version of RestSharp ?

[MissingMethodException: Méthode introuvable : 'RestSharp.RestClientOptions RestSharp.RestClient.get_Options()'.]
   PostFinanceCheckout.Client.Configuration.set_BasePath(String value) +0
   PostFinanceCheckout.Client.Configuration..ctor(String applicationUserID, String authenticationKey, RestClientOptions restClientOptions) +165

Regards.

**Comment by theodorspringwallee** [comment]
Dear [Eskissimo](https://github.com/Eskissimo)

We have updated to the RestSharp version 110.2.0.

See more detailed information under: https://github.com/pfpayments/csharp-sdk/releases

Best regards
