### ISSUE TITLE
Input string not Base64 on CustomerService call

### ISSUE THREAD

**Issue by Netclick19** [pfpayments/csharp-sdk#9]
Hi,
after upgrading to 7.0.1  version on this call.

                    var filters = new List<EntityQueryFilter>
                    {
                        new EntityQueryFilter(EntityQueryFilterType.LEAF)
                        {
                            FieldName = "customerId",
                            Operator = CriteriaOperator.EQUALS,
                            Value = paymentInfo.customerID
                        }
                    };

                    var entityQuery = new EntityQuery
                    {
                        Filter = new EntityQueryFilter(EntityQueryFilterType.AND)
                        {
                            Children = filters
                        }
                    };

                    var customers = customerService.Search(spaceId, entityQuery);

I got this error:

FormatException:  L'input non è una stringa Base 64 valida poiché contiene un carattere  non Base 64, più di due caratteri di riempimento oppure un carattere non  corretto tra i caratteri di riempimento.
--
Stack Trace | in System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)       in System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)       in System.Convert.FromBase64String(String s)       in PostFinanceCheckout.Client.ApiClient.CalculateHmac(String signature)       in PostFinanceCheckout.Client.ApiClient.AuthenticationHeaders(Method method, String path, List`1 queryParams)       in  PostFinanceCheckout.Client.ApiClient.PrepareRequest(String path, Method  method, List`1 queryParams, Object postBody, Dictionary`2 headerParams,  Dictionary`2 defaultHeaderParams, Dictionary`2 formParams, Dictionary`2  fileParams, Dictionary`2 pathParams, String contentType)       in  PostFinanceCheckout.Client.ApiClient.CallApi(String path, Method  method, List`1 queryParams, Object postBody, Dictionary`2 headerParams,  Dictionary`2 formParams, Dictionary`2 fileParams, Dictionary`2  pathParams, String contentType, Int32 timeout)       in PostFinanceCheckout.Service.CustomerService.SearchWithHttpInfo(Nullable`1 spaceId, EntityQuery query)       in PostFinanceCheckout.Service.CustomerService.Search(Nullable`1 spaceId, EntityQuery query)

Can you help me to solve the problem?

Thank you for your support.

Kind regards.

**Comment by theodorspringwallee** [comment]
Dear [Netclick19](https://github.com/Netclick19)

What is the value you have for "paymentInfo.customerID"?

It's important to differentiate between the ID of the customer entity (id) and the customer identifier (customerId) you are using within the filter. You see those values when you open a customer entity on the PFC portal:
![Bildschirmfoto 2023-10-03 um 10 13 30](https://github.com/pfpayments/csharp-sdk/assets/85299706/63f5560d-2f68-4ed8-8287-b9b4fb7d4d5b)

Here an example how to search a customer over its identifier (customerId):
```
var filters = new List<EntityQueryFilter>
                {
                    new EntityQueryFilter(EntityQueryFilterType.LEAF)
                    {
                        FieldName = "customerId",
                        Operator = CriteriaOperator.EQUALS,
                        Value = 6
                    }
                };

            var entityQuery = new EntityQuery
            {
                Filter = new EntityQueryFilter(EntityQueryFilterType.AND)
                {
                    Children = filters
                }
            };

            var customers = customerService.Search(spaceId, entityQuery);
            foreach(Customer customer in customers)
            {
                System.Console.WriteLine("Customer ID: " + customer.CustomerId);
                System.Console.WriteLine("Customer Entity ID: " + customer.Id);
            }
```

Please let me know if this solves your issue.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [Netclick19](https://github.com/Netclick19)

With the newest C# SDK release its working for me.

Please can you try the following code (just replace it with your auth credentials and customerId):
```
public class PFCServiceHelperClass
{
    private CustomerService customerService;
    private long spaceId;
    private String appUserId;
    private String appUserKey;

    public PFCServiceHelperClass()
    {
        this.spaceId = ;
        this.appUserId = "";
        this.appUserKey = "";
        var configuration = new Configuration(this.appUserId, this.appUserKey);
        this.customerService = new CustomerService(configuration);
    }

    static void Main(string[] args)
    {
        try
        {
            PFCServiceHelperClass pfcServiceHelperClass = new PFCServiceHelperClass();
            var filters = new List<EntityQueryFilter>
                {
                    new EntityQueryFilter(EntityQueryFilterType.LEAF)
                    {
                        FieldName = "customerId",
                        Operator = CriteriaOperator.EQUALS,
                        Value = 6
                    }
                };

            var entityQuery = new EntityQuery
            {
                Filter = new EntityQueryFilter(EntityQueryFilterType.AND)
                {
                    Children = filters
                }
            };

            var customers = pfcServiceHelperClass.customerService.Search(pfcServiceHelperClass.spaceId, entityQuery);
            foreach (Customer customer in customers)
            {
                System.Console.WriteLine("Customer ID: " + customer.CustomerId);
                System.Console.WriteLine("Customer Entity ID: " + customer.Id);
            }

        }
        catch (Exception ex)
        {
            System.Console.Write("Exception: " + ex.Message.ToString());
            System.Console.Write("Exception: " + ex.StackTrace.ToString());
        }
    }

}
```

If this still does not work for you, please contact the PF Support (https://www.postfinance.ch/en/support/products/onlineshop-pos/postfinance-checkout-contact-and-support.html) and share with them your space ID and the concerned customer ID, which does not work for the query.

Best regards

**Comment by Netclick19** [comment]
Hi,
the problem was solved.
Thank you for your support.
